# docker build -f docker/Dockerfile.dev -t fhrozen/vllm-omni:builder-cuda13-u24 .
FROM nvidia/cuda:13.0.3-cudnn-devel-ubuntu24.04

RUN apt-get update && apt-get install -y \
    git \
    curl \
    wget \
    vim \
    ca-certificates \
    build-essential \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ENV UV_HTTP_TIMEOUT=500
ENV UV_INDEX_STRATEGY="unsafe-best-match"
ENV UV_PYTHON_INSTALL_DIR=/workspace/.uv-bin
ENV UV_CACHE_DIR=/workspace/.uv_cache
ENV UV_INSTALL_DIR=/opt/uv/bin

RUN curl -LsSf https://astral.sh/uv/install.sh | sh \
    && rm -rf /var/lib/apt/lists/*

ENV PATH="$UV_INSTALL_DIR:$PATH"
RUN mkdir -p /workspace
WORKDIR /workspace
RUN git config --global --add safe.directory /workspace
